### ISSUE TITLE
Content - Training output

### ISSUE THREAD

**Issue by erinmgraham** [carpentries-incubator/intro-image-classification-cnn#2]
Need to talk about the output that is automatically displayed when fitting a model, eg: 

Epoch 1/10 

1563/1563 [==============================] - 5s 3ms/step - loss: 1.4011 - accuracy: 0.5046 - val_loss: 1.3644 - val_accuracy: 0.5243 

Content could go in the intro ep at step 6 or build ep, both are getting lengthy

**Comment by isaac-jennings** [comment]
Hi @erinmgraham, I have added some info to ep 01 explaining epoch, loss, accuracy, val_loss and val_accuracy, but agree both options are lengthy as is. Formatted with a drop down to try save on space. What do you think?

**Comment by isaac-jennings** [comment]
Rendering the drop down didn't look like it would align with the design handbook. Have changed to callout for now.

**Comment by erinmgraham** [comment]
Sorry Isaac, I didn't get a chance to look at your drop downs before you rolled back your changes. What tag did you use to create them? I found something in the sandpaper docs about spoilers: https://carpentries.github.io/sandpaper-docs/episodes.html#use-spoilers-instead-of-floating-solution-blocks

**Comment by erinmgraham** [comment]
Returned IJ content to as is (without spoiler, callout or other). Important enough topic to make proper content.
