### ISSUE TITLE
ep 05 discuss neurons in more detail

### ISSUE THREAD

**Issue by erinmgraham** [carpentries-incubator/intro-image-classification-cnn#20]
consider adding neuron discussion to hyperparameters

**Comment by isaac-jennings** [comment]
Hi @erinmgraham, I have started with an opening paragraph describing neurons under Step 9. Looking for some relatable pictures and mathematical representations of the input vectors, weights, and output. Will comment back here when ready for review.

**Comment by erinmgraham** [comment]
Hey Isaac, there's a lot of talk about neurons in ep 03 build which might be a better place for it. I was originally thinking of adding it as a tune but now that I've gone through just about all the content and code (as of ten minutes ago) I would be happy to wait until we see how long what we have now takes.

**Comment by erinmgraham** [comment]
Hey Isaac, there's a lot of talk about neurons in ep 03 build which might be a better place for it. I was originally thinking of adding it as a tune but now that I've gone through just about all the content and code (as of ten minutes ago) I would be happy to wait until we see how long what we have now takes.

**Comment by isaac-jennings** [comment]
Ah yes, there is heaps in ep03. I will delete what I pushed for ep05 on neurons (can always add it back later). It prompted me to reword and shorten the paragraph on hyper parameters too - I made it so clunky originally.

**Comment by erinmgraham** [comment]
Per IJ comments can close this issue
