### ISSUE TITLE
Episode 02 prepare dataset function local variable declared by not used.

### ISSUE THREAD

**Issue by isaac-jennings** [carpentries-incubator/intro-image-classification-cnn#27]
[Episode 02, Challenge 02](https://carpentries-incubator.github.io/intro-image-classification-cnn/02-image-data.html#challenge-create-a-function-to-prepare-the-dataset) declaring a custom function to prepare dataset from train images and test labels declares `test images` but is not used further in the function.

Could we remove local variable declaration?

**Comment by isaac-jennings** [comment]
@jasonbell13 and I have checked out local var test_images and suggest deletion as train_labels are char values which do not need normalisation.

**Comment by erinmgraham** [comment]
As part of script rewrite for second trial the prepare_dataset() function only deals with train_images and train_labels. Note this means when we do get to use the test_images we need to normalize them.
