### ISSUE TITLE
Update package installations for Mac/Linux

### ISSUE THREAD

**Issue by marklcrowe** [carpentries-incubator/intro-image-classification-cnn#30]
Install the Required Packages (https://carpentries-incubator.github.io/intro-image-classification-cnn/index.html#install-the-required-packages) refers to "anaconda prompt" which doesn't exist on the Mac (or probably Linux). Both just use Terminal for this step (despite the instructions explicitly saying to use Spotlight to find the app on Mac).

**Comment by jasonbell13** [comment]
I have moved the Windows, Mac and Linux "Using Conda to install packages" content to different "tabs" on the setup document.  I have added new "Mac" instructions to remove the mention of a anaconda prompt and instead using just using the terminal.
