### ISSUE TITLE
Set correct working directory in code

### ISSUE THREAD

**Issue by marklcrowe** [carpentries-incubator/intro-image-classification-cnn#31]
At various points in the code, data is written/read from the "fit_outputs" directory. In the zip archive, this is within the "scripts" directory. But following the code as per the guide, the working directory does not get set to "scripts" so instead it tries to access a "fit_outputs" directory either in the home or intro-image-classification-cnn directories (and when writing, seems to silently create that directory). We should probably either use absolute paths or explicity set the working directory to the right location.

**Comment by erinmgraham** [comment]
When running complete scripts (Run All) inside the Spyder IDE, it automatically changes the working directory to where the script is located. Preference is to use relative paths, not absolute paths. 

TODO Add content explaining this functionality in Spyder and reminding users how to set explicitly when running

**Comment by erinmgraham** [comment]
Added instructions to setup detailing how to set working directory in spyder and also added callout to ep 01 to remind everyone what to do.
